import Head from 'next/head';
import { 
  Box,
  Text,
  Flex,
  Link
} from "@chakra-ui/react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Laravel | documentation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
    </>

  )
}
