import Head from 'next/head';
import { 
  Box,
  Text,
  Flex,
  Link
} from "@chakra-ui/react";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Laravel | documentation</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Flex  h="calc(100vh - 70px)" justify="center" align="center" flexDir="column" overflowY="scroll" className="theScroll" >
        <Text as="h2"  fontSize="30px" letterSpacing="7px" color="gray.400">
          🧑🏿‍💻
        </Text>

          <Text as="h2" fontSize="90px" letterSpacing="7px" color="gray.400">
            Laravel
          </Text>

          <Text  fontSize="1rem" color="gray.400" mb="1">
            Essa documentação foi desenvolvida para me auxiliar nos meus projetos.
          </Text>
          <Text  fontSize="1rem" color="gray.200"  mb="1">
            Mas nada impede q você estude por ela. 😉
          </Text>
          <Text color="gray.400">
            Dê um rolê pela SideBar e veja se tem algo que possa te ajudar.  
          </Text>

        <Box mt="140px" >

          <Link 
            border="solid 1px transparent"
            p="5"
            fontSize="1rem"
            fontWeight="bold"
            borderRadius="8px"
            href="https://laravel.com/docs/8.x"
            target="_blank"
            _hover={{
              background: "#232930",
              border:"solid 1px #232930",
              color:"#ff2d20"
            }}
            color="gray.600"
          >
            Acessar documentação oficial
          </Link>
        </Box>


      </Flex>
    </div>
  )
}
